# Generated by Django 5.0.4 on 2024-04-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('endereco', models.TextField(max_length=100)),
                ('aparelho', models.TextField(max_length=100)),
                ('problema', models.TextField(max_length=100)),
                ('valor_pecas', models.IntegerField()),
                ('mao_de_obra', models.IntegerField()),
                ('total_servico', models.IntegerField()),
                ('pediu_nota', models.TextField(max_length=30)),
            ],
        ),
    ]
